version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/work
    tty: true
    stdin_open: true
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - TZ=Asia/Tokyo
    command: flask run -h 0.0.0.0 -p 5000
